LIBNAME=	libclabs
SRC=		hw_cluster_labs.c
OBJ=		hw_cluster_labs.o
HEADER=		hw_cluster_labs.h

TOP= ../../..
include $(TOP)/configure.mk
include $(TOP)/common.mk
include build.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
