DIR=ccgost
CC=cc
INCLUDES= -I../../include
CFLAG=-g
MAKEFILE= Makefile
AR= ar r
CFLAGS= $(INCLUDES) $(CFLAG)
LIB=$(TOP)/libcrypto.a

TOP= ../..
include $(TOP)/common.mk
include build.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
