LIBNAME=	libibmca
SRC=		hw_ibmca.c
OBJ=		hw_ibmca.o
HEADER=		hw_ibmca.h

TOP= ../../..
include $(TOP)/configure.mk
include $(TOP)/common.mk
include build.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
